#' Motion Sense Dataset: Measurements of user acceleration and pitch attitude collected by smartphones from 24 individuals performing four distinct activities: jogging, walking, sitting, and standing.
#'
#' This dataset includes time-series data generated by accelerometer and gyroscope sensors.
#' A total of 24 participants in a range of gender, age, weight, and height performed 4 activities in the same environment 
#' and conditions: downstairs, upstairs, walking, jogging, sitting, and standing.
#'
#' @name MotionSenseDataset
#' @format A functional time series object of class `funts` with the following fields:
#' @examples
#' \dontrun{
#' # Load the Motion Sense Dataset
#' data("motion_sense_data")
#' }
NULL